/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class controleur_InterfaceCjava */

#ifndef _Included_controleur_InterfaceCjava
#define _Included_controleur_InterfaceCjava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     controleur_InterfaceCjava
 * Method:    MenuIndexation_Texte
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_controleur_InterfaceCjava_MenuIndexation_1Texte
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
