recherche : moteur.c moteur.h ../pile_dynamique.c ../pile_dynamique.h ../descripteur.c ../descripteur.h ../controle_descripteur.c ../controle_descripteur.h
	gcc -c -Wall moteur.c -lm -g
	gcc -c -Wall ../pile_dynamique.c -lm -g
	gcc -c -Wall ../descripteur.c -lm -g
	gcc -c -Wall ../controle_descripteur.c -lm -g
	gcc -o recherche.out moteur.o pile_dynamique.o descripteur.o controle_descripteur.o